#!/bin/sh

# Exit script if any statement returns a non-true return value
set -e

filesChanged=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD \
  | grep -c "package-lock.json" \
)

if [ "$filesChanged" != "0" ]; then
  npm install --no-audit --progress=false
fi
