#
# CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1

#
# Orbs - https://circleci.com/docs/2.0/orb-concepts/#quick-start
#
# Shareable packages of configuration elements, including jobs commands,
# and executors
#

orbs:
  slack: circleci/slack@4.6.0

#
# Executors - https://circleci.com/docs/2.0/executor-intro/
#
# The underlying technology or environment in which to run a job
#

executors:
  node-lts:
    docker:
      - image: cimg/node:lts

#
# YAML variable templates
#

JOB_DEFAULTS: &JOB_DEFAULTS
  executor: node-lts
  working_directory: ~/m

#
# Jobs - https://circleci.com/docs/2.0/configuration-reference/#jobs
#
# Atomic parts of the pipeline that will be composed and configured in one or
# more Workflows
#

jobs:
  setup:
    <<: *JOB_DEFAULTS
    steps:
      - checkout
      - restore_cache:
          name: '[circleci] Restore cached "node_modules" folder'
          keys:
            - &CACHE_KEY_NODE_MODULES 'm-{{ arch }}-{{ checksum
              "package-lock.json" }}'
            - &CACHE_KEY_FALLBACK "m-"
      - run:
          name: "[npm]: Install packages"
          command: |
            npm install --no-audit
      - save_cache:
          paths:
            - node_modules
          key: *CACHE_KEY_NODE_MODULES
      - persist_to_workspace:
          root: &WORKSPACE_ROOT "~/"
          paths:
            - "m"

  test:
    <<: *JOB_DEFAULTS
    steps:
      - attach_workspace:
          at: *WORKSPACE_ROOT
      - run:
          name: "[eslint]: Lint"
          command: |
            npm run lint
      - run:
          name: "[tape]: Unit Test"
          command: |
            npm run test

  coverage:
    <<: *JOB_DEFAULTS
    steps:
      - attach_workspace:
          at: *WORKSPACE_ROOT
      - run:
          name: "[c8,coveralls]: Publish test coverage to Coveralls"
          command: |
            npm run coverage

  publish:
    <<: *JOB_DEFAULTS
    steps:
      - attach_workspace:
          at: *WORKSPACE_ROOT
      - run:
          name: "[swc]: Compile application"
          command: |
            npm run build
      - run:
          name:
            "[semantic-release]: Update version, generate release, publish npm
            package"
          command: |
            npm run publish

#
# Workflows - https://circleci.com/docs/2.0/workflows/
#
# Treat workflows as a jobs/commands pipe:
# cmd1 -p1 lorem | cmd2 -foo bar | ... | cmdN)
#

workflows:
  publish_@latest:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - setup
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - coverage

  publish_@next:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - next
      - test:
          requires:
            - setup
      - coverage:
          requires:
            - test
      - publish:
          requires:
            - coverage

  test_feature_branches:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
                - master
                - next
      - test:
          requires:
            - setup
