module.exports = {
  filter  : require( "./array__filter/filter" ),
  filterBy: require( "./array__filter-by/filter-by" ),
  findBy  : require( "./array__find-by/find-by" ),
  flatten : require( "./array__flatten/flatten" ),
  forEach : require( "./array__for-each/for-each" ),
  has     : require( "./array__has/has" ),
  hasWith : require( "./array__has-with/has-with" ),
  indexBy : require( "./array__index-by/index-by" ),
  map     : require( "./array__map/map" ),
  push    : require( "./array__push/push" ),
  reduce  : require( "./array__reduce/reduce" ),
  remove  : require( "./array__remove/remove" ),
  toggle  : require( "./array__toggle/toggle" ),
  zipToObj: require( "./array__zip-to-obj/zip-to-obj" ),
  i       : require( "./core__i/i" ),
  ifThen  : require( "./core__if-then/if-then" ),
  isEmpty : require( "./core__is-empty/is-empty" ),
  pipe    : require( "./core__pipe/pipe" ),
  raise   : require( "./core__raise/raise" ),
  type    : require( "./core__type/type" ),
  coinToss: require( "./number__coin-toss/coin-toss" ),
  random  : require( "./number__random/random" ),
  get     : require( "./object__get/get" ),
  hasKey  : require( "./object__has-key/has-key" ),
  merge   : require( "./object__merge/merge" ),
  pick    : require( "./object__pick/pick" ),
  set     : require( "./object__set/set" ),
}
